### PR TITLE
[SPARK-49019] Use `try-with-resources` to test `KubernetesClientFactory.buildKubernetesClient`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to use `try-with-resources` to test `KubernetesClientFactory.buildKubernetesClient`.

### Why are the changes needed?

To be safe during the testing.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @viirya ?

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @huaxingao ?

**Review by viirya — APPROVED** [review]

**Review by huaxingao — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya and @huaxingao .

**Comment by dongjoon-hyun** [comment]
Merged to main.

**Pull request closed without merging**
