### PR TITLE
[SPARK-48382][FOLLOWUP] Use `final` keyword for the applicable variables

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a follow-up to use `final` keyword for the applicable variables.

- #12

### Why are the changes needed?

To be clear about the semantic of the variables.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @jiangzho ?

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @viirya ?

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @huaxingao ?

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya and @huaxingao .

**Comment by dongjoon-hyun** [comment]
Merged to main.

**Pull request closed without merging**
