### PR TITLE
[SPARK-49590] Fix `javaVersion` to `jdkVersion` in E2E `spark-versions` test template

### PR DESCRIPTION
**Pull request by jiangzho**
### What changes were proposed in this pull request?

This PR corrects an invalid spec in e2e test template - `javaVersion` -> `jdkVersion` .

https://github.com/apache/spark-kubernetes-operator/blob/bc422fd4524f8139e934123cfe78d1833009026c/spark-operator-api/src/main/java/org/apache/spark/k8s/operator/spec/RuntimeVersions.java#L39

### Why are the changes needed?

The invalid test template causes e2e to fail e.g. https://github.com/apache/spark-kubernetes-operator/actions/runs/10745816799/job/29942467715?pr=118

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

CIs

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by jiangzho** [comment]
cc @viirya can you please help to review ?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

To @jiangzho , here are two recommendation for you.

1. You had better refer code like the following at the exact line number which shows the code snippet directly.
 
Screenshot 2024-09-10 at 13 16 07

2. This is a general recommendation. Please use PR title as a place to show your goal of pull request instead of describing the problem. That's the main difference between PR title and JIRA title. For example, a good PR title would be about what to do and how to do instead of describing the problem like `E2E test template includes invalid spec field`.

**Comment by dongjoon-hyun** [comment]
cc @TQJADE , too.

**Comment by dongjoon-hyun** [comment]
Merged to main.

**Review by viirya — COMMENTED** [review]
Looks good to me.

**Pull request closed without merging**
