### PR TITLE
[SPARK-49389] Support `master|worker` container templates

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to support `master` container and `worker` container templates.

### Why are the changes needed?

Previously, pod template throws exceptions on containers whose name is `master` or `worker` because two `master|worker` containers were created. After this PR, the problem is resolved.
- #80 

### Does this PR introduce _any_ user-facing change?

No, this is a new unreleased feature.

### How was this patch tested?

For now, we need to run manual tests.
```
$ ./gradlew build buildDockerImage spark-operator-api:relocateGeneratedCRD -x check
$ helm install spark-kubernetes-operator -f build-tools/helm/spark-kubernetes-operator/values.yaml build-tools/helm/spark-kubernetes-operator/
$ kubectl apply -f examples/cluster-with-template.yaml
$ kubectl get pod -l spark-role=master -oyaml | yq '.items[0].spec.containers[0].resources'
limits:
  cpu: "2"
  memory: 2Gi
requests:
  cpu: "2"
  memory: 2Gi
```

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
BTW, the PR labeler works! 😄

**Comment by dongjoon-hyun** [comment]
cc @jiangzho and @viirya

**Comment by viirya** [comment]
> BTW, the PR labeler works! 😄

Nice!

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya . Merged to main.

**Pull request closed without merging**
