### PR TITLE
[SPARK-47745] Add License to Spark Operator repository

### PR DESCRIPTION
**Pull request by jiangzho**
### What changes were proposed in this pull request?

This PR aims to add ASF license file.

### Why are the changes needed?

To receive a code contribution.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

Manual review.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Thank you for making a small and reviewable PR, @jiangzho .
- First, please make an Apache Spark JIRA and use it from now.
- Second, please address the above two comments.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for updating.

**Comment by dongjoon-hyun** [comment]
To @viirya , how do you want to manage the versioning of this module? It seems that we need to decide the versioning plan and policy before starting to merge.

**Comment by dongjoon-hyun** [comment]
Gentle ping, @viirya .

**Comment by viirya** [comment]
> It seems that we need to decide the versioning plan and policy before starting to merge.

@dongjoon-hyun Sorry for missing first ping. Can you describe it more? I'm not sure about what versioning plan and policy. For general versioning plan, will it be different to Spark versioning policy?

**Comment by dongjoon-hyun** [comment]
Specifically, if you are going to merge this PR, how can you resolve this PR and the corresponding JIRA? What is the fixed version?
- SPARK-47745

**Comment by dongjoon-hyun** [comment]
For the record, this PR is currently blocked by the following VOTE.
- https://lists.apache.org/thread/s9m1pvjogfwpkhjbythpojdvj05yylz7
```
[VOTE] Add new `Versions` in Apache Spark JIRA for Versioning of Spark Operator
```

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Yea, let's wait for the vote on the versioning of this Spark operator. Thanks.

**Comment by viirya** [comment]
The vote was passed today. I created `kubernetes-operator-0.1.0` in Spark JIRA. All Spark k8s operator related JIRA tickets can use this version now.

**Comment by dongjoon-hyun** [comment]
Thank you! Then, let's roll in it.

**Comment by dongjoon-hyun** [comment]
Thank you, @jiangzho and @viirya . It's merged.

Screenshot 2024-04-16 at 8 09 33 AM

BTW, to @jiangzho , I revised the PR description according to the community guide and added your new ID to Apache Spark contributor group again.

**Comment by viirya** [comment]
Thank you @jiangzho @dongjoon-hyun

**Pull request closed without merging**
